_extends: github-apps-config-next
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts:
          - 'ci/circleci: test-v14.19'
          - 'ci/circleci: test-v16.14'
      enforce_admins: true
      restrictions:
        users: []
        teams: []
