language: node_js
node_js:
- stable

env:
  global:
  - secure: gvZRVZCR4omwAzHzwyb9b9qU8Iav1vDS0QowibTudABF+FT4kLTL6rb7ucjV+q0AKFzu1TJJp+qrgu0dmLrmI8N7y6dLoSmKbq8TkdxYJVCpXtOw4VngRCiknIDISmrYHPwgzrSGi4625McTHwXtoFDln/ftk568F2l7f0H7SMRb/jEjBTGgVvKC+a0blOLGOmyTBUENhPO5NU2kXRayjqgWTbo60uO8WP6UH9haGC2PpVEA4lrgJmWx3bcFTIEYbcKV7ZDLHPTnC1RXR/fEdAAnZM8//oe+3SdUjhHAxPGyvtBZY1nGk0rcLn1uzh879tVPv8fz9cB5lWjDeI7mTJQ8ZRCosAhZWSRxIPnGHCi0iDOU+zZJqPsmHAUYM5mShepCcDfSF2FuCA4I8NILHsU1PoHZ4eHvvhx3xWjeYa4KMjZXcVeuJWfqCRoluTrndjgi16pkTvDOKyPnA1uO2tgVZz7TE7lvNxU0YvxPvO+TxxGuX1N9uv6gur9zvk06TAVvoRMwNxY6iV1pbLchQwGu7S7UPbLG95WV9dwmlH6wXz+I281CHaEL2SzD0D8inznKTLq5ztxOww7XZtyNP1m7fxM+eD69PqHsuEW1/DFNgS5BHyVWFGV0p7qberFi0+aGKYNk494ZtyjntSrZ8Yj0CDU9BFzuiU/vWFQ/QbQ=

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: packages/x-docs/public
  committer-from-gh: true
  verbose: true
  on:
    branch: master
