# THIS IS A CUSTOM CIRCLE CONFIG, IT WAS NOT GENERATED

references:

  container_config_node8: &container_config_node8
    working_directory: ~/project/build
    docker:
      - image: circleci/node:8-browsers

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_keys: &npm_cache_keys
    keys:
        - v1-dependency-npm-{{ checksum "package.json" }}-
        - v1-dependency-npm-{{ checksum "package.json" }}
        - v1-dependency-npm-

  cache_npm_cache: &cache_npm_cache
    save_cache:
        key: v1-dependency-npm-{{ checksum "package.json" }}-{{ epoch }}
        paths:
        - ./node_modules/

  restore_npm_cache: &restore_npm_cache
    restore_cache:
        <<: *npm_cache_keys

  filters_only_master: &filters_only_master
    branches:
      only: master

  filters_ignore_master: &filters_ignore_master
    branches:
      ignore: master

  filters_ignore_tags: &filters_ignore_tags
    tags:
      ignore: /.*/

  filters_version_tag: &filters_version_tag
    tags:
      only:
        - /^v?\d+\.\d+\.\d+(?:-beta\.\d+)?$/
    branches:
      ignore: /.*/

version: 2

jobs:

  build:
    <<: *container_config_node8
    steps:
      - checkout
      - run:
          name: Checkout next-ci-shared-helpers
          command: git clone --depth 1 git@github.com:Financial-Times/next-ci-shared-helpers.git .circleci/shared-helpers
      - *restore_npm_cache
      - run:
          name: Install project dependencies
          command: make install
      - run:
          name: Run the project build task
          command: make build
      # - run:
      #     name: shared-helper / generate-build-state-artifacts
      #     command: .circleci/shared-helpers/helper-generate-build-state-artifacts
      #     when: always
      - *cache_npm_cache
      - store_artifacts:
          path: build-state
          destination: build-state
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  test:
    <<: *container_config_node8
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: make test
      #    environment:
      #       JEST_JUNIT_OUTPUT: test-results/jest/results.xml
      # - store_test_results:
      #     path: test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: test-results

  publish:
    <<: *container_config_node8
    steps:
      - *attach_workspace
      - run:
          name: shared-helper / npm-store-auth-token
          command: .circleci/shared-helpers/helper-npm-store-auth-token
      - run:
          name: athloi publish
          command: npx athloi version ${CIRCLE_TAG} && npx athloi publish -- --access=public

workflows:

  version: 2

  build-test:
    jobs:
      - build:
          filters:
            <<: *filters_ignore_tags
      - test:
          requires:
            - build

  build-test-publish:
    jobs:
      - build:
          filters:
            <<: *filters_version_tag
      - test:
          filters:
            <<: *filters_version_tag
          requires:
            - build
      - publish:
          filters:
            <<: *filters_version_tag
          requires:
            - test

notify:
  webhooks:
    - url: https://ft-next-webhooks.herokuapp.com/circleci2-workflow
